[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "scikit-learn>=1.7.1",
    "streamlit>=1.47.0",
]
